config/routes.rb
Rails.application.routes.draw do

    get '/app_details' => 'apps#show_details'

    resources :apps , only: [:index] do
      collection do
        post 'search'
      end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController

	require 'rubygems'
    require 'market_bot'

	def index
		@collection = MarketBot::Play::Chart::COLLECTIONS
        @categories = MarketBot::Play::Chart::CATEGORIES
        # debugger
	end

	def search
		@apps = MarketBot::Play::Chart.new(params[:Collection], params[:Categories])
		@apps.update
		# debugger
		respond_to do |format|
			format.js
		end
	end

	def show_details
		@app = MarketBot::Play::App.new(params[:app_id])
		@app.update
		@image = params[:image]
		#debugger
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/views/apps/_app_list.html.erb
<% @apps.result.first(20).each do |app| %>
	<div>
		<h4>App Name: <%= link_to app[:title], app_details_path(app_id: app[:store_url].split('?id=')[1], image: app[:icon_url]) %></h4>
		<%= image_tag(app[:icon_url], size: '100x100') %><br/>
		<strong> Rating : <%= app[:stars]%> </strong> , <strong> App URL : <%= app[:store_url] %> </strong>
		 <hr/>
	</div>
<% end %>

app/views/apps/search.js.erb
$('#app_list').html("<%= j (render partial: 'app_list') %>");

app/views/apps/show_details.html.erb
<div>
	<h4>App Name: <%= @app.title %> </h4>

	<%= image_tag(@image) %> <br/><br/>

	<strong>Rating : <%= @app.rating %></strong><br/><br/>

	<strong> Description :</strong> <br/><%= @app.description.html_safe %> <hr/>

	<strong>Reviews: <%= @app.reviews.count %> </strong><br/>

		<% @app.reviews.each do |review| %>
			<strong>Author: <%= review[:author] %>, Rating: <%= review[:score] %> </strong><br/>, 
			<strong>Title: </strong><%= review[:title] %><br/>,
			<strong>Comment: </strong><%= review[:text] %> <hr/>
		<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scraper</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<h3>Google Play Store</h3>
	<%= yield %>

</body>
</html>